# Generated by Django 4.2.5 on 2023-10-02 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Accenture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField(null=True)),
                ("input_format", models.TextField(null=True)),
                ("output_format", models.TextField(null=True)),
                ("correct_ans", models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Adobe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField(null=True)),
                ("input_format", models.TextField(null=True)),
                ("output_format", models.TextField(null=True)),
                ("correct_ans", models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Amazon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField(null=True)),
                ("input_format", models.TextField(null=True)),
                ("output_format", models.TextField(null=True)),
                ("correct_ans", models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Apple",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField(null=True)),
                ("input_format", models.TextField(null=True)),
                ("output_format", models.TextField(null=True)),
                ("correct_ans", models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Atos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField(null=True)),
                ("input_format", models.TextField(null=True)),
                ("output_format", models.TextField(null=True)),
                ("correct_ans", models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Capgemini",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField(null=True)),
                ("input_format", models.TextField(null=True)),
                ("output_format", models.TextField(null=True)),
                ("correct_ans", models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Cisco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField(null=True)),
                ("input_format", models.TextField(null=True)),
                ("output_format", models.TextField(null=True)),
                ("correct_ans", models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Coginzant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField(null=True)),
                ("input_format", models.TextField(null=True)),
                ("output_format", models.TextField(null=True)),
                ("correct_ans", models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=122)),
                ("email", models.CharField(max_length=122)),
                ("phone", models.CharField(max_length=12)),
                ("desc", models.TextField()),
                ("date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Delloite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField(null=True)),
                ("input_format", models.TextField(null=True)),
                ("output_format", models.TextField(null=True)),
                ("correct_ans", models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="EY",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField(null=True)),
                ("input_format", models.TextField(null=True)),
                ("output_format", models.TextField(null=True)),
                ("correct_ans", models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Facebook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField(null=True)),
                ("input_format", models.TextField(null=True)),
                ("output_format", models.TextField(null=True)),
                ("correct_ans", models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Google",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField(null=True)),
                ("input_format", models.TextField(null=True)),
                ("output_format", models.TextField(null=True)),
                ("correct_ans", models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="IBM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField(null=True)),
                ("input_format", models.TextField(null=True)),
                ("output_format", models.TextField(null=True)),
                ("correct_ans", models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Infosys",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField(null=True)),
                ("input_format", models.TextField(null=True)),
                ("output_format", models.TextField(null=True)),
                ("correct_ans", models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="mahindra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField(null=True)),
                ("input_format", models.TextField(null=True)),
                ("output_format", models.TextField(null=True)),
                ("correct_ans", models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Microsoft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField(null=True)),
                ("input_format", models.TextField(null=True)),
                ("output_format", models.TextField(null=True)),
                ("correct_ans", models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Netflix",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField(null=True)),
                ("input_format", models.TextField(null=True)),
                ("output_format", models.TextField(null=True)),
                ("correct_ans", models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="PWC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField(null=True)),
                ("input_format", models.TextField(null=True)),
                ("output_format", models.TextField(null=True)),
                ("correct_ans", models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="TCS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField(null=True)),
                ("input_format", models.TextField(null=True)),
                ("output_format", models.TextField(null=True)),
                ("correct_ans", models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="TM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField(null=True)),
                ("input_format", models.TextField(null=True)),
                ("output_format", models.TextField(null=True)),
                ("correct_ans", models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Wipro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField(null=True)),
                ("input_format", models.TextField(null=True)),
                ("output_format", models.TextField(null=True)),
                ("correct_ans", models.TextField(null=True)),
            ],
        ),
    ]
